# Generated by Django 3.2.12 on 2022-02-11 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=80)),
                ('care_type', models.CharField(choices=[('gnral', '일반치료'), ('imp', '임플란트'), ('align', '치아교정'), ('beauty', '치아미백')], max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('text', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='pages.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
