# Generated by Django 3.2.12 on 2022-03-15 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qnapost',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qna', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qnaanswerpost',
            name='qnas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='posts.qnapost'),
        ),
        migrations.AddField(
            model_name='noticepost',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noticephoto',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notice_photos', to='posts.noticepost'),
        ),
        migrations.AddField(
            model_name='newsphoto',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_photos', to='posts.newspost'),
        ),
        migrations.AddField(
            model_name='bnaphoto',
            name='bna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bna_photos', to='posts.bnapost'),
        ),
    ]
