# Generated by Django 3.2.12 on 2022-02-11 02:27

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='NATIONAL'),
        ),
    ]
