# Generated by Django 3.2.12 on 2022-03-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_bnaphoto_bnapost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticepost',
            name='notice_type',
            field=models.CharField(choices=[('event', '이벤트'), ('notice', '공지')], max_length=20),
        ),
    ]
