# Generated by Django 3.2.12 on 2022-03-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_noticepost_notice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticepost',
            name='notice_type',
            field=models.CharField(choices=[('이벤트', 'event'), ('공지', 'notice')], max_length=20),
        ),
    ]
